### ISSUE TITLE
feature extractors

### ISSUE THREAD

**Issue by 7HHHHH** [xrli-U/MuSc#10]
Very good work! Do you support other feature extractors, or can you only choose from these three?

**Comment by xrli-U** [comment]
These three are the most classic ViT pre-training models. You can replace it with any pre-trained vision transformer such as MAE or SimCLR. It can also be replaced with swin transformer, but the AC and AS results are not good, please refer to Table 8 in our paper.

**Comment by giraffeGYH** [comment]
该方法能够使用CNN网络进行特征提取？比如resnet50等，效果如何？

**Comment by xrli-U** [comment]
> 该方法能够使用CNN网络进行特征提取？比如resnet50等，效果如何？

可以将特征提取器换成CNN，相比于ViT指标会有所下降。通常来讲特征提取器提取的特征越好，最终的分类和分割的指标会越高

**Comment by giraffeGYH** [comment]
我尝试将特征提取器更换为ResNet50出现了错误，如何修改呢？
![image](https://github.com/xrli-U/MuSc/assets/44046018/99005b9c-1985-482d-b3a5-e4ae9861226a)

**Comment by giraffeGYH** [comment]
我尝试将特征提取的骨干网络修改为ResNet50，可是出现了错误，请问如何修改呢？（直接替换clip？）

**Comment by xrli-U** [comment]
> 我尝试将特征提取的骨干网络修改为ResNet50，可是出现了错误，请问如何修改呢？（直接替换clip？） ![image](https://private-user-images.githubusercontent.com/44046018/345973087-4c7c15b1-44e1-47ae-94f8-afa2aee10d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDUwMjMsIm5iZiI6MTcyMDE0NDcyMywicGF0aCI6Ii80NDA0NjAxOC8zNDU5NzMwODctNGM3YzE1YjEtNDRlMS00N2FlLTk0ZjgtYWZhMmFlZTEwZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAxNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTI2ZDMxM2IzNWU5M2JmOWViZTJlNGYxOTIzNWI3M2QxNDJkOGUyODM2ZTU5MThjYzY2ZGEwY2Y4MjA0ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUTF0iuyF8Rvjm2LafoykBZZPXgrzKj3qUv9NeiUhDE)

当前程序并没有编写兼容resent的代码，请使用torchvision.models.resnet50自定义resnet网络

**Comment by xrli-U** [comment]
> 我尝试将特征提取的骨干网络修改为ResNet50，可是出现了错误，请问如何修改呢？（直接替换clip？） ![image](https://private-user-images.githubusercontent.com/44046018/345973087-4c7c15b1-44e1-47ae-94f8-afa2aee10d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDUwMjMsIm5iZiI6MTcyMDE0NDcyMywicGF0aCI6Ii80NDA0NjAxOC8zNDU5NzMwODctNGM3YzE1YjEtNDRlMS00N2FlLTk0ZjgtYWZhMmFlZTEwZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAxNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTI2ZDMxM2IzNWU5M2JmOWViZTJlNGYxOTIzNWI3M2QxNDJkOGUyODM2ZTU5MThjYzY2ZGEwY2Y4MjA0ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUTF0iuyF8Rvjm2LafoykBZZPXgrzKj3qUv9NeiUhDE)

或者可以等待近两个月，我们会更新新版本的musc，其中会加入对更多feature extractor的兼容

**Comment by giraffeGYH** [comment]
感谢您的回复。我想复现full-shto的实验结果，请问musc的full-shot条件如何设置？

**Comment by xrli-U** [comment]
> 感谢您的回复。我想复现full-shto的实验结果，请问musc的full-shot条件如何设置？

官方代码会在近两个月进行更新，如果您想要自己修改的话，feature extract和LNAMD模块保持不变，mutual scoring模块中需要将打分的对象进行替换

**Comment by giraffeGYH** [comment]
好的，谢谢您。
