### ISSUE TITLE
对于'good'的处理

### ISSUE THREAD

**Issue by HHHLLL1** [xrli-U/MuSc#14]
我看了一下代码，数据处理时是把定义为‘good’的图片过滤掉了，那模型会出现把‘good’图片识别成缺陷图片的情况吗，作者有做过这个测试吗

**Comment by xrli-U** [comment]
您好，我并未发现您所说的“在数据处理时把定义为good的图片过滤掉”这个操作，可以详细说一下在哪个文件的多少行吗？我唯一能想到可能产生误解的是./models/musc.py文件的第104行，这里是最终进行可视化时的处理，由于要进行单图归一可视化，good图像中不包含缺陷，可视化没有意义，如果要对good图像进行可视化，可以在sh脚本中添加**--vis_type whole_norm**

**Comment by HHHLLL1** [comment]
抱歉，是我弄错了，感谢您的回复，谢谢
