### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by lyl58** [xrli-U/MuSc#17]
您好，拜读了一下您的文章，请问在推理时是必须多个图片同时处理吗？单个图片无法得到其他图片的评分，假如检测时出现批量同样缺陷（如对应位置物料缺失），这些情况是无法检测成功的是吗？不知道我的理解是否有误，期待您的回复

**Comment by xrli-U** [comment]
> 您好，拜读了一下您的文章，请问在推理时是必须多个图片同时处理吗？单个图片无法得到其他图片的评分，假如检测时出现批量同样缺陷（如对应位置物料缺失），这些情况是无法检测成功的是吗？不知道我的理解是否有误，期待您的回复

是的，这种情况没有理由会会认为对应位置物料缺失是一种缺陷，比如有块木板左上角有个洞，如果所有木板都长这样就没有理由会认为这个洞是缺陷，这有可能是故意设计成这样的

**Comment by lyl58** [comment]
> > 您好，拜读了一下您的文章，请问在推理时是必须多个图片同时处理吗？单个图片无法得到其他图片的评分，假如检测时出现批量同样缺陷（如对应位置物料缺失），这些情况是无法检测成功的是吗？不知道我的理解是否有误，期待您的回复
> 
> 是的，这种情况没有理由会会认为对应位置物料缺失是一种缺陷，比如有块木板左上角有个洞，如果所有木板都长这样就没有理由会认为这个洞是缺陷，这有可能是故意设计成这样的

好的，非常感谢您的回复
