### ISSUE TITLE
测试问题backbone的选择

### ISSUE THREAD

**Issue by lyl58** [xrli-U/MuSc#18]
请问backbone设置为ViT-B-32时，feature_layers设置为多少呢？期待您的回复。

**Comment by xrli-U** [comment]
> 请问backbone设置为ViT-B-32时，feature_layers设置为多少呢？期待您的回复。

feature_layers按照文中所说均匀划分取3到4层即可。我不建议您使用ViT-B-32，因为这里的patch size是32有些过大了，无法进行细粒度的分割。

**Comment by lyl58** [comment]
好的，感谢您
