### ISSUE TITLE
该设定是否合理，想与作者进行探讨

### ISSUE THREAD

**Issue by HuWeiYu** [xrli-U/MuSc#20]
大家都是国人，我就不写英语了。不得不说MuSc确实非常强力，作者脑洞也很大让我佩服。可是这种设定是否存在信息泄露的问题，就好像batch normalization一样，尽管MuSC使用的是未标记的测试去做embedding，但是这相当于提前知道了测试集的分布，在缺陷检测领域，这个是否合理呢？

**Comment by HuWeiYu** [comment]
我说一个比喻，就是，比起别人是随堂考试，MuSC尽管不能作弊提前知道答案，但是却提前拿到了这个试卷，这是否是一个公平的比较。我刚读完论文，因为效果过于惊艳遂来看看代码，也许有理解偏驳，还请作者海涵。

**Comment by zhouyu-hust** [comment]
> 我说一个比喻，就是，比起别人是随堂考试，MuSC尽管不能作弊提前知道答案，但是却提前拿到了这个试卷，这是否是一个公平的比较。我刚读完论文，因为效果过于惊艳遂来看看代码，也许有理解偏驳，还请作者海涵。

Hi 您好！关于无标签数据潜在信息的应用，ACR（NeurIPS2023）是首次使用了无标签数据进行零样本异常检测，而MuSc的核心贡献是仅使用无标签数据做零样本异常检测，无需任何训练，关于无标签数据的应用，和ACR的比较是一致和公平的，且MuSc的难度更大，因没有任何的先验学习（相当于不经过任何学习环节，即参加考试）。这也是作者做该工作的一个核心出发点，即目前产业界面临着模型迁移性的痛点问题，在进行跨时间、跨产线、跨产品的场景迁移的时候，需要重新训练模型，通过不进行任何基于训练数据的学习，直接使用无标签数据的潜在判决性质，可以有效的应对和缓解模型迁移性的问题。

**Comment by HuWeiYu** [comment]
感谢您及时的回复！
